<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WorldsStatesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $table = config('worldcities.table.state');

        DB::table($table)->truncate();

        DB::table($table)->insert(array(
            0 =>
                array(
                'id' => 1,
                'country_id' => 58,
                'name' => json_encode(['en' => 'Chungcheongbuk-do', 'zh' => '庆尚北道']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => '43',
                'has_city' => 1,
            ),
            1 =>
                array(
                'id' => 2,
                'country_id' => 58,
                'name' => json_encode(['en' => 'Chungcheongnam-do', 'zh' => '庆尚南道']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => '44',
                'has_city' => 1,
            ),
            2 =>
                array(
                'id' => 3,
                'country_id' => 58,
                'name' => json_encode(['en' => 'Daegu', 'zh' => '大邱']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => '27',
                'has_city' => 1,
            ),
            3 =>
                array(
                'id' => 4,
                'country_id' => 58,
                'name' => json_encode(['en' => 'Gangwon-do', 'zh' => '江原道']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => '42',
                'has_city' => 1,
            ),
            4 =>
                array(
                'id' => 5,
                'country_id' => 58,
                'name' => json_encode(['en' => 'Gyeonggi-do', 'zh' => '京畿道']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => '49',
                'has_city' => 1,
            ),
            5 =>
                array(
                'id' => 6,
                'country_id' => 58,
                'name' => json_encode(['en' => 'Gyeongsangbuk-do', 'zh' => '全罗北道']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => '47',
                'has_city' => 1,
            ),
            6 =>
                array(
                'id' => 7,
                'country_id' => 58,
                'name' => json_encode(['en' => 'Gyeongsangnam-do', 'zh' => '全罗南道']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => '48',
                'has_city' => 1,
            ),
            7 =>
                array(
                'id' => 8,
                'country_id' => 58,
                'name' => json_encode(['en' => 'Jeollabuk-do', 'zh' => '忠清北道']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => '45',
                'has_city' => 1,
            ),
            8 =>
                array(
                'id' => 9,
                'country_id' => 58,
                'name' => json_encode(['en' => 'Jeollanam-do', 'zh' => '忠清南道']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => '46',
                'has_city' => 1,
            ),
            9 =>
                array(
                'id' => 10,
                'country_id' => 87,
                'name' => json_encode(['en' => 'Johor', 'zh' => '柔佛']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'jh',
                'has_city' => 1,
            ),
            10 =>
                array(
                'id' => 11,
                'country_id' => 87,
                'name' => json_encode(['en' => 'Kedah', 'zh' => '吉打']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'kd',
                'has_city' => 1,
            ),
            11 =>
                array(
                'id' => 12,
                'country_id' => 87,
                'name' => json_encode(['en' => 'Kelantan', 'zh' => '吉兰丹']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'kn',
                'has_city' => 1,
            ),
            12 =>
                array(
                'id' => 13,
                'country_id' => 87,
                'name' => json_encode(['en' => 'Kuala Lumpur', 'zh' => '吉隆坡']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'kl',
                'has_city' => 1,
            ),
            13 =>
                array(
                'id' => 14,
                'country_id' => 87,
                'name' => json_encode(['en' => 'Labuan', 'zh' => '纳闽']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'lb',
                'has_city' => 1,
            ),
            14 =>
                array(
                'id' => 15,
                'country_id' => 87,
                'name' => json_encode(['en' => 'Malacca', 'zh' => '马六甲']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ml',
                'has_city' => 1,
            ),
            15 =>
                array(
                'id' => 16,
                'country_id' => 87,
                'name' => json_encode(['en' => 'Negeri Sembilan', 'zh' => '森美兰']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ns',
                'has_city' => 1,
            ),
            16 =>
                array(
                'id' => 17,
                'country_id' => 87,
                'name' => json_encode(['en' => 'Pahang', 'zh' => '彭亨']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'pg',
                'has_city' => 1,
            ),
            17 =>
                array(
                'id' => 18,
                'country_id' => 87,
                'name' => json_encode(['en' => 'Perak', 'zh' => '霹雳']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'pk',
                'has_city' => 1,
            ),
            18 =>
                array(
                'id' => 19,
                'country_id' => 87,
                'name' => json_encode(['en' => 'Perlis', 'zh' => '玻璃市']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ps',
                'has_city' => 1,
            ),
            19 =>
                array(
                'id' => 20,
                'country_id' => 87,
                'name' => json_encode(['en' => 'Pulau Pinang', 'zh' => '槟榔屿']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ph',
                'has_city' => 1,
            ),
            20 =>
                array(
                'id' => 21,
                'country_id' => 87,
                'name' => json_encode(['en' => 'Sabah', 'zh' => '沙巴']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'sb',
                'has_city' => 1,
            ),
            21 =>
                array(
                'id' => 22,
                'country_id' => 87,
                'name' => json_encode(['en' => 'Sarawak', 'zh' => '沙捞越']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'sr',
                'has_city' => 1,
            ),
            22 =>
                array(
                'id' => 23,
                'country_id' => 87,
                'name' => json_encode(['en' => 'Selangor', 'zh' => '雪兰莪']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'sl',
                'has_city' => 1,
            ),
            23 =>
                array(
                'id' => 24,
                'country_id' => 87,
                'name' => json_encode(['en' => 'Terengganu', 'zh' => '丁加奴']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'tr',
                'has_city' => 1,
            ),
            24 =>
                array(
                'id' => 25,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Anhui', 'zh' => '安徽']),
                'abbr' => json_encode(['zh' => '徽']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '安徽省']),
                'code' => '34',
                'has_city' => 1,
            ),
            25 =>
                array(
                'id' => 26,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Beijing', 'zh' => '北京']),
                'abbr' => json_encode(['zh' => '京']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '北京市']),
                'code' => '11',
                'has_city' => 1,
            ),
            26 =>
                array(
                'id' => 27,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Chongqing', 'zh' => '重庆']),
                'abbr' => json_encode(['zh' => '渝']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '重庆市']),
                'code' => '50',
                'has_city' => 1,
            ),
            27 =>
                array(
                'id' => 28,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Fujian', 'zh' => '福建']),
                'abbr' => json_encode(['zh' => '闽']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '福建省']),
                'code' => '35',
                'has_city' => 1,
            ),
            28 =>
                array(
                'id' => 29,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Gansu', 'zh' => '甘肃']),
                'abbr' => json_encode(['zh' => '甘']),
                'alias' => json_encode(['zh' => '陇']),
                'full_name' => json_encode(['zh' => '甘肃省']),
                'code' => '62',
                'has_city' => 1,
            ),
            29 =>
                array(
                'id' => 30,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Guangdong', 'zh' => '广东']),
                'abbr' => json_encode(['zh' => '粤']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '广东省']),
                'code' => '44',
                'has_city' => 1,
            ),
            30 =>
                array(
                'id' => 31,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Guangxi', 'zh' => '广西']),
                'abbr' => json_encode(['zh' => '桂']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '广西壮族自治区']),
                'code' => '45',
                'has_city' => 1,
            ),
            31 =>
                array(
                'id' => 32,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Guizhou', 'zh' => '贵州']),
                'abbr' => json_encode(['zh' => '贵']),
                'alias' => json_encode(['zh' => '黔']),
                'full_name' => json_encode(['zh' => '贵州市']),
                'code' => '52',
                'has_city' => 1,
            ),
            32 =>
                array(
                'id' => 33,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Hainan', 'zh' => '海南']),
                'abbr' => json_encode(['zh' => '琼']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '河南省']),
                'code' => '46',
                'has_city' => 1,
            ),
            33 =>
                array(
                'id' => 34,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Hebei', 'zh' => '河北']),
                'abbr' => json_encode(['zh' => '冀']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '河北省']),
                'code' => '13',
                'has_city' => 1,
            ),
            34 =>
                array(
                'id' => 35,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Heilongjiang', 'zh' => '黑龙江']),
                'abbr' => json_encode(['zh' => '黑']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '黑龙江省']),
                'code' => '23',
                'has_city' => 1,
            ),
            35 =>
                array(
                'id' => 36,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Henan', 'zh' => '河南']),
                'abbr' => json_encode(['zh' => '豫']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '河南省']),
                'code' => '41',
                'has_city' => 1,
            ),
            36 =>
                array(
                'id' => 37,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Hubei', 'zh' => '湖北']),
                'abbr' => json_encode(['zh' => '鄂']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '湖北省']),
                'code' => '42',
                'has_city' => 1,
            ),
            37 =>
                array(
                'id' => 38,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Hunan', 'zh' => '湖南']),
                'abbr' => json_encode(['zh' => '湘']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '湖南省']),
                'code' => '43',
                'has_city' => 1,
            ),
            38 =>
                array(
                'id' => 39,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Inner Mongolia', 'zh' => '内蒙古']),
                'abbr' => json_encode(['zh' => '蒙']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '内蒙古自治区']),
                'code' => '15',
                'has_city' => 1,
            ),
            39 =>
                array(
                'id' => 40,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Jiangsu', 'zh' => '江苏']),
                'abbr' => json_encode(['zh' => '苏']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '江苏省']),
                'code' => '32',
                'has_city' => 1,
            ),
            40 =>
                array(
                'id' => 41,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Jiangxi', 'zh' => '江西']),
                'abbr' => json_encode(['zh' => '赣']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '江西省']),
                'code' => '36',
                'has_city' => 1,
            ),
            41 =>
                array(
                'id' => 42,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Jilin', 'zh' => '吉林']),
                'abbr' => json_encode(['zh' => '吉']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '吉林省']),
                'code' => '22',
                'has_city' => 1,
            ),
            42 =>
                array(
                'id' => 43,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Liaoning', 'zh' => '辽宁']),
                'abbr' => json_encode(['zh' => '辽']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '辽宁省']),
                'code' => '21',
                'has_city' => 1,
            ),
            43 =>
                array(
                'id' => 44,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Ningxia', 'zh' => '宁夏']),
                'abbr' => json_encode(['zh' => '宁']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '宁夏回族自治区']),
                'code' => '64',
                'has_city' => 1,
            ),
            44 =>
                array(
                'id' => 45,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Qinghai', 'zh' => '青海']),
                'abbr' => json_encode(['zh' => '青']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '青海省']),
                'code' => '63',
                'has_city' => 1,
            ),
            45 =>
                array(
                'id' => 46,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Shaanxi', 'zh' => '陕西']),
                'abbr' => json_encode(['zh' => '陕']),
                'alias' => json_encode(['zh' => '秦']),
                'full_name' => json_encode(['zh' => '陕西省']),
                'code' => '61',
                'has_city' => 1,
            ),
            46 =>
                array(
                'id' => 47,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Shandong', 'zh' => '山东']),
                'abbr' => json_encode(['zh' => '鲁']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '山东省']),
                'code' => '37',
                'has_city' => 1,
            ),
            47 =>
                array(
                'id' => 48,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Shanghai', 'zh' => '上海']),
                'abbr' => json_encode(['zh' => '沪']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '上海市']),
                'code' => '31',
                'has_city' => 1,
            ),
            48 =>
                array(
                'id' => 49,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Shanxi', 'zh' => '山西']),
                'abbr' => json_encode(['zh' => '晋']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '山西省']),
                'code' => '14',
                'has_city' => 1,
            ),
            49 =>
                array(
                'id' => 50,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Sichuan', 'zh' => '四川']),
                'abbr' => json_encode(['zh' => '川']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '四川省']),
                'code' => '51',
                'has_city' => 1,
            ),
            50 =>
                array(
                'id' => 51,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Taiwan', 'zh' => '台湾']),
                'abbr' => json_encode(['zh' => '台']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '台湾省']),
                'code' => '71',
                'has_city' => 1,
            ),
            51 =>
                array(
                'id' => 52,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Tianjin', 'zh' => '天津']),
                'abbr' => json_encode(['zh' => '津']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '天津市']),
                'code' => '12',
                'has_city' => 1,
            ),
            52 =>
                array(
                'id' => 53,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Tibet', 'zh' => '西藏']),
                'abbr' => json_encode(['zh' => '藏']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '西藏自治区']),
                'code' => '54',
                'has_city' => 1,
            ),
            53 =>
                array(
                'id' => 54,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Xinjiang', 'zh' => '新疆']),
                'abbr' => json_encode(['zh' => '新']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '新疆维吾尔自治区']),
                'code' => '65',
                'has_city' => 1,
            ),
            54 =>
                array(
                'id' => 55,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Yunnan', 'zh' => '云南']),
                'abbr' => json_encode(['zh' => '云']),
                'alias' => json_encode(['zh' => '滇']),
                'full_name' => json_encode(['zh' => '云南省']),
                'code' => '53',
                'has_city' => 1,
            ),
            55 =>
                array(
                'id' => 56,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Zhejiang', 'zh' => '浙江']),
                'abbr' => json_encode(['zh' => '浙']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '浙江省']),
                'code' => '33',
                'has_city' => 1,
            ),
            56 =>
                array(
                'id' => 57,
                'country_id' => 148,
                'name' => json_encode(['en' => 'England', 'zh' => '英格兰']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'eng',
                'has_city' => 1,
            ),
            57 =>
                array(
                'id' => 58,
                'country_id' => 148,
                'name' => json_encode(['en' => 'Northern Ireland', 'zh' => '北爱尔兰']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'nir',
                'has_city' => 1,
            ),
            58 =>
                array(
                'id' => 59,
                'country_id' => 148,
                'name' => json_encode(['en' => 'Scotland', 'zh' => '苏格兰']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'sct',
                'has_city' => 1,
            ),
            59 =>
                array(
                'id' => 60,
                'country_id' => 148,
                'name' => json_encode(['en' => 'Wales', 'zh' => '威尔士']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'wls',
                'has_city' => 1,
            ),
            60 =>
                array(
                'id' => 61,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Alabama', 'zh' => '阿拉巴马']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'al',
                'has_city' => 1,
            ),
            61 =>
                array(
                'id' => 62,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Alaska', 'zh' => '阿拉斯加']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ak',
                'has_city' => 1,
            ),
            62 =>
                array(
                'id' => 63,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Arizona', 'zh' => '亚利桑那']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'az',
                'has_city' => 1,
            ),
            63 =>
                array(
                'id' => 64,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Arkansas', 'zh' => '阿肯色']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ar',
                'has_city' => 1,
            ),
            64 =>
                array(
                'id' => 65,
                'country_id' => 167,
                'name' => json_encode(['en' => 'California', 'zh' => '加利福尼亚']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ca',
                'has_city' => 1,
            ),
            65 =>
                array(
                'id' => 66,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Colorado', 'zh' => '科罗拉多']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'co',
                'has_city' => 1,
            ),
            66 =>
                array(
                'id' => 67,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Connecticut', 'zh' => '康涅狄格']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ct',
                'has_city' => 1,
            ),
            67 =>
                array(
                'id' => 68,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Delaware', 'zh' => '特拉华']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'de',
                'has_city' => 1,
            ),
            68 =>
                array(
                'id' => 69,
                'country_id' => 167,
                'name' => json_encode(['en' => 'District of Columbia', 'zh' => '哥伦比亚特区']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'dc',
                'has_city' => 1,
            ),
            69 =>
                array(
                'id' => 70,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Florida', 'zh' => '佛罗里达']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'fl',
                'has_city' => 1,
            ),
            70 =>
                array(
                'id' => 71,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Georgia', 'zh' => '佐治亚']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ga',
                'has_city' => 1,
            ),
            71 =>
                array(
                'id' => 72,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Hawaii', 'zh' => '夏威夷']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'hi',
                'has_city' => 1,
            ),
            72 =>
                array(
                'id' => 73,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Idaho', 'zh' => '爱达荷']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'id',
                'has_city' => 1,
            ),
            73 =>
                array(
                'id' => 74,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Illinois', 'zh' => '伊利诺斯']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'il',
                'has_city' => 1,
            ),
            74 =>
                array(
                'id' => 75,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Indiana', 'zh' => '印第安那']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'in',
                'has_city' => 1,
            ),
            75 =>
                array(
                'id' => 76,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Iowa', 'zh' => '爱荷华']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ia',
                'has_city' => 1,
            ),
            76 =>
                array(
                'id' => 77,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Kansas', 'zh' => '堪萨斯']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ks',
                'has_city' => 1,
            ),
            77 =>
                array(
                'id' => 78,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Kentucky', 'zh' => '肯塔基']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ky',
                'has_city' => 1,
            ),
            78 =>
                array(
                'id' => 79,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Louisiana', 'zh' => '路易斯安那']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'la',
                'has_city' => 1,
            ),
            79 =>
                array(
                'id' => 80,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Maine', 'zh' => '缅因']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'me',
                'has_city' => 1,
            ),
            80 =>
                array(
                'id' => 81,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Maryland', 'zh' => '马里兰']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'md',
                'has_city' => 1,
            ),
            81 =>
                array(
                'id' => 82,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Massachusetts', 'zh' => '马萨诸塞']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ma',
                'has_city' => 1,
            ),
            82 =>
                array(
                'id' => 83,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Michigan', 'zh' => '密歇根']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'mi',
                'has_city' => 1,
            ),
            83 =>
                array(
                'id' => 84,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Minnesota', 'zh' => '明尼苏达']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'mn',
                'has_city' => 1,
            ),
            84 =>
                array(
                'id' => 85,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Mississippi', 'zh' => '密西西比']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ms',
                'has_city' => 1,
            ),
            85 =>
                array(
                'id' => 86,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Missouri', 'zh' => '密苏里']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'mo',
                'has_city' => 1,
            ),
            86 =>
                array(
                'id' => 87,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Montana', 'zh' => '蒙大拿']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'mt',
                'has_city' => 1,
            ),
            87 =>
                array(
                'id' => 88,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Nebraska', 'zh' => '内布拉斯加']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ne',
                'has_city' => 1,
            ),
            88 =>
                array(
                'id' => 89,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Nevada', 'zh' => '内华达']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'nv',
                'has_city' => 1,
            ),
            89 =>
                array(
                'id' => 90,
                'country_id' => 167,
                'name' => json_encode(['en' => 'New Hampshire', 'zh' => '新罕布什尔']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'nh',
                'has_city' => 1,
            ),
            90 =>
                array(
                'id' => 91,
                'country_id' => 167,
                'name' => json_encode(['en' => 'New Jersey', 'zh' => '新泽西']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'nj',
                'has_city' => 1,
            ),
            91 =>
                array(
                'id' => 92,
                'country_id' => 167,
                'name' => json_encode(['en' => 'New Mexico', 'zh' => '新墨西哥']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'nm',
                'has_city' => 1,
            ),
            92 =>
                array(
                'id' => 93,
                'country_id' => 167,
                'name' => json_encode(['en' => 'New York', 'zh' => '纽约']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ny',
                'has_city' => 1,
            ),
            93 =>
                array(
                'id' => 94,
                'country_id' => 167,
                'name' => json_encode(['en' => 'North Carolina', 'zh' => '北卡罗来纳']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'nc',
                'has_city' => 1,
            ),
            94 =>
                array(
                'id' => 95,
                'country_id' => 167,
                'name' => json_encode(['en' => 'North Dakota', 'zh' => '北达科他']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'nd',
                'has_city' => 1,
            ),
            95 =>
                array(
                'id' => 96,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Ohio', 'zh' => '俄亥俄']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'oh',
                'has_city' => 1,
            ),
            96 =>
                array(
                'id' => 97,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Oklahoma', 'zh' => '俄克拉荷马']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ok',
                'has_city' => 1,
            ),
            97 =>
                array(
                'id' => 98,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Oregon', 'zh' => '俄勒冈']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'or',
                'has_city' => 1,
            ),
            98 =>
                array(
                'id' => 99,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Pennsylvania', 'zh' => '宾夕法尼亚']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'pa',
                'has_city' => 1,
            ),
            99 =>
                array(
                'id' => 100,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Rhode Island', 'zh' => '罗德岛']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ri',
                'has_city' => 1,
            ),
            100 =>
                array(
                'id' => 101,
                'country_id' => 167,
                'name' => json_encode(['en' => 'South Carolina', 'zh' => '南卡罗来纳']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'sc',
                'has_city' => 1,
            ),
            101 =>
                array(
                'id' => 102,
                'country_id' => 167,
                'name' => json_encode(['en' => 'South Dakota', 'zh' => '南达科他']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'sd',
                'has_city' => 1,
            ),
            102 =>
                array(
                'id' => 103,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Tennessee', 'zh' => '田纳西']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'tn',
                'has_city' => 1,
            ),
            103 =>
                array(
                'id' => 104,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Texas', 'zh' => '德克萨斯']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'tx',
                'has_city' => 1,
            ),
            104 =>
                array(
                'id' => 105,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Utah', 'zh' => '犹他']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'ut',
                'has_city' => 1,
            ),
            105 =>
                array(
                'id' => 106,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Vermont', 'zh' => '佛蒙特']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'vt',
                'has_city' => 1,
            ),
            106 =>
                array(
                'id' => 107,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Virginia', 'zh' => '维吉尼亚']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'va',
                'has_city' => 1,
            ),
            107 =>
                array(
                'id' => 108,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Washington', 'zh' => '华盛顿']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'wa',
                'has_city' => 1,
            ),
            108 =>
                array(
                'id' => 109,
                'country_id' => 167,
                'name' => json_encode(['en' => 'West Virginia', 'zh' => '西佛吉尼亚']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'wv',
                'has_city' => 1,
            ),
            109 =>
                array(
                'id' => 110,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Wisconsin', 'zh' => '威斯康星']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'wi',
                'has_city' => 1,
            ),
            110 =>
                array(
                'id' => 111,
                'country_id' => 167,
                'name' => json_encode(['en' => 'Wyoming', 'zh' => '怀俄明']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'wy',
                'has_city' => 1,
            ),
            111 =>
                array(
                'id' => 112,
                'country_id' => 170,
                'name' => json_encode(['en' => 'Canberra', 'zh' => '堪培拉']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'act',
                'has_city' => 1,
            ),
            112 =>
                array(
                'id' => 113,
                'country_id' => 170,
                'name' => json_encode(['en' => 'New South Wales', 'zh' => '新南威尔士']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'nsw',
                'has_city' => 1,
            ),
            113 =>
                array(
                'id' => 114,
                'country_id' => 170,
                'name' => json_encode(['en' => 'Northern Territory', 'zh' => '北部地区']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'nt',
                'has_city' => 1,
            ),
            114 =>
                array(
                'id' => 115,
                'country_id' => 170,
                'name' => json_encode(['en' => 'Queensland', 'zh' => '昆士兰']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'qld',
                'has_city' => 1,
            ),
            115 =>
                array(
                'id' => 116,
                'country_id' => 170,
                'name' => json_encode(['en' => 'South Australia', 'zh' => '南澳大利亚']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'sa',
                'has_city' => 1,
            ),
            116 =>
                array(
                'id' => 117,
                'country_id' => 170,
                'name' => json_encode(['en' => 'Tasmania', 'zh' => '塔斯马尼亚']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'tas',
                'has_city' => 1,
            ),
            117 =>
                array(
                'id' => 118,
                'country_id' => 170,
                'name' => json_encode(['en' => 'Victoria', 'zh' => '维多利亚']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'vic',
                'has_city' => 1,
            ),
            118 =>
                array(
                'id' => 119,
                'country_id' => 170,
                'name' => json_encode(['en' => 'Western Australia', 'zh' => '西澳大利亚']),
                'abbr' => null,
                'alias' => null,
                'full_name' => null,
                'code' => 'wa',
                'has_city' => 1,
            ),
            119 =>
                array(
                'id' => 121,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Hongkong', 'zh' => '香港']),
                'abbr' => json_encode(['zh' => '港']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '香港特别行政区']),
                'code' => 'hk',
                'has_city' => 0,
            ),
            120 =>
                array(
                'id' => 122,
                'country_id' => 101,
                'name' => json_encode(['en' => 'Macau', 'zh' => '澳门']),
                'abbr' => json_encode(['zh' => '澳']),
                'alias' => null,
                'full_name' => json_encode(['zh' => '澳门特别行政区']),
                'code' => 'mo',
                'has_city' => 0,
            ),
        ));
    }
}